### PR TITLE
Update pom.xml

### PR DESCRIPTION
**Pull request by MonishK2002**

### CODE REVIEW

**Comment by hsluoyz** [comment]
@MonishK2002 fix CI:

image

**Comment by MonishK2002** [comment]
@hsluoyz I noticed that my recent PR to update the casdoor-java-sdk version in the casdoor-spring-boot-starter project was closed. Could you please provide more details or feedback on why it was closed? I want to ensure that any necessary adjustments are made and that the update can be successfully integrated.

**Comment by hsluoyz** [comment]
@MonishK2002 

1. CI errors
2. No context in PR title or content

**Comment by MonishK2002** [comment]
@hsluoyz 
Thank you for your feedback regarding the CI errors.

I understand that my PR lacks context in the title and content. I will update the PR title and provide a more detailed description to clarify the changes made and their purpose.

Once I make these adjustments, I will notify you for further review. Thank you for your guidance and support.

**Pull request closed without merging**
