### PR TITLE
Update Casdoor Java SDK version to 1.34.0

### PR DESCRIPTION
**Pull request by MonishK2002**

### CODE REVIEW

**Comment by hsluoyz** [comment]
@MonishK2002 

1. Don't use ChatGPT to write PR description
2. Pass all CI

**Comment by MonishK2002** [comment]
@hsluoyz 
From now on, I won't use the chatGPT. could you please explain what you mean by CI?

**Comment by hsluoyz** [comment]
@MonishK2002 all should be green

image

**Comment by hsluoyz** [comment]
Replaced by: https://github.com/casdoor/casdoor-spring-boot-starter/pull/51

**Pull request closed without merging**
